# Generated by Django 2.2 on 2019-04-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uplaod_date',
            new_name='upload_date',
        ),
    ]
