# Generated by Django 2.2 on 2019-04-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
